### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by softwaretailoring** [dlt-rilmta/emtsv#14] opened 2020-12-10 08:58 UTC
I would like to use the Docker container from a Windows environment via REST API.
I installed everything as is in the documentation, then I got '{"message": "Internal Server Error"}' after API call.
Any known issue about this?
What can I do?

**Comment by dlazesz** [comment] 2020-12-10 09:02
Which version/commit of emtsv do you use? Could you attach the docker logs?

**Comment by softwaretailoring** [comment] 2020-12-10 09:18
Thank you for your quick response!

I've used these commands:
docker pull mtaril/emtsv:latest
docker run --rm -p5000:5000 -it mtaril/emtsv

Here is the docker log:
[docker_error_20201210.txt](https://github.com/dlt-rilmta/emtsv/files/5671562/docker_error_20201210.txt)

**Comment by dlazesz** [comment] 2020-12-10 09:35
Judging from the log file this issue is the exact duplicate of #13 
We are working hard on a new release with more accurate tests to prevent these kind of issues in the future.

You have two options:
Wait for the new release, which is due soon, or create an own docker image from the latest sources (this requires a Linux system).

Thank you for your understanding.

I close this issue. We may continue the discussion in #13

**Closed by dlazesz** 2020-12-10 09:35 UTC
